development:
  admin:
    name: admin
    password: admin
  facebook:
    key: 511845342165164
    secret: bba6703db68e38c220281c2cc04d142b

test:
  admin:
    name: admin
    password: admin

production:
